## Put comments here that give an overall description of what your
## functions do

## The functions below create a mechanism for calculating the inverse
## of an invertible square matrix and storing the results in cache.
## Computing the inverse of a matrix is processing intensive so the
## function will first check to see if the inverse of the requested 
## matrix has been calculated before and return the cached value 
## rather than spending resources on computing it again.

## Example:
## > mat <- rbind(c(1,2),c(3,4))
## > a <- makeCacheMatrix(mat)
## > cacheSolve(a)
##      [,1] [,2]
## [1,] -2.0  1.0
## [2,]  1.5 -0.5
## > cacheSolve(a)
## getting cached data
##      [,1] [,2]
## [1,] -2.0  1.0
## [2,]  1.5 -0.5

## Write a short comment describing this function

## This function takes a matrix as input and generates a list as output
## that contains functions to store and retrieve the matrix from cache,
## and store and retrieve the inverse of that matrix generated ny the
## solve() function from cache.

makeCacheMatrix <- function(x = matrix()) {
    s <- NULL
    set <- function(y) {
        x <<- y
        s <<- NULL
    }
    get <- function() x
    setsolve <- function(solve) s <<- solve
    getsolve <- function() s
    list(set = set,
         get = get,
         setsolve = setsolve,
         getsolve = getsolve)
}


## Write a short comment describing this function

## This function takes the list of functions generated by the makeCacheMatrix()
## function and first checks the cache to see if the inverse of the matrix has 
## been calculated and stored before.  If it has, that solution matrix is 
## retrieved from cache and returned, otherwise the solution matrix is 
## calculated, stored in cache, and returned.

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    s <- x$getsolve()
    if(!is.null(s)) {
        message("getting cached data")
        return(s)
    }
    data <- x$get()
    s <- solve(data, ...)
    x$setsolve(s)
    s
}
